# Generated by Django 6.0 on 2025-12-10 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0001_initial'),
        ('suscripciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandato',
            name='suscripcion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mandato', to='suscripciones.suscripcion'),
        ),
        migrations.AddField(
            model_name='pago',
            name='suscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='suscripciones.suscripcion'),
        ),
    ]
