# Generated by Django 6.0 on 2025-12-10 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('captacion', '0001_initial'),
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='captadorprofile',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captadores_supervisados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='captadorprofile',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_captador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrocaptacion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_captacion', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='sesioncaptacion',
            name='captador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='captacion.captadorprofile'),
        ),
        migrations.AddField(
            model_name='sesioncaptacion',
            name='punto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones', to='captacion.puntocaptacion'),
        ),
        migrations.AddField(
            model_name='registrocaptacion',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='captacion.sesioncaptacion'),
        ),
    ]
