# Generated by Django 6.0 on 2025-12-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CambioPlanSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEstadoSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=15)),
                ('estado_nuevo', models.CharField(max_length=15)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACTIVA', 'Activa'), ('PAUSADA', 'Pausada'), ('CANCELADA', 'Cancelada'), ('FINALIZADA', 'Finalizada')], default='PENDIENTE', max_length=15)),
                ('metodo_pago', models.CharField(choices=[('PAC', 'PAC'), ('PAT', 'PAT'), ('TRANSFERENCIA', 'Transferencia'), ('WEBPAY', 'Webpay'), ('OTRO', 'Otro')], default='PAC', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('dia_cobro', models.PositiveSmallIntegerField(default=5, help_text='Día del mes en que se intenta el cobro recurrente.')),
                ('monto_actual', models.DecimalField(decimal_places=2, help_text='Monto vigente de la suscripción.', max_digits=12)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
